databases:
  - name: lab-scheduler-db
    databaseName: lab_scheduler_db
    user: lab_scheduler_db_user
    plan: free
    region: oregon

services:
  - type: web
    name: lab-scheduler
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn lab_scheduler.src.main:app
    region: oregon
    plan: free
    envVars:
      - key: FLASK_SECRET_KEY
        value: a_very_strong_random_secret_key_prod_456!@#
      - key: ADMIN_PASSWORD
        value: admin123
      # Configuração manual da DATABASE_URL usando a string de conexão interna
      - key: DATABASE_URL
        value: postgresql://lab_sch
