services:
  - type: web
    name: lab-scheduler
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn src.main:app
    region: oregon
    plan: free
    envVars:
      - key: FLASK_SECRET_KEY
        value: a_very_strong_random_secret_key_prod_456!@#
      - key: ADMIN_PASSWORD
        value: admin123
      - key: DATABASE_URL
        value: sqlite:///lab_scheduler.db
